# Generated by Django 3.2 on 2024-11-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldenGymApp', '0004_novedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
