# Generated by Django 3.2 on 2024-11-20 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoldenGymApp', '0005_alter_novedad_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso_actual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('press_banca', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sentadilla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_muerto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='GoldenGymApp.cliente')),
            ],
        ),
    ]
