# Generated by Django 5.1.4 on 2024-12-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldenGymApp', '0010_cliente_encargado_novedad_autor_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='membresia',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='suscripcion_activa',
            field=models.BooleanField(default=False),
        ),
    ]
